name: Create additional tags for each release

on:
  release:
    types: [published]
  workflow_dispatch: # If manually triggered, clarify which release to create the additional tags for
    inputs:
      releaseTag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name || github.event.inputs.releaseTag }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Create additional tags
      run: |
        REF=${{ github.event.release.tag_name || github.event.inputs.releaseTag }}
        ARTIFACT_IDS=('google-cloud-shared-dependencies' 'api-common' 'gax')
        for ARTIFACT_ID in "${ARTIFACT_IDS[@]}"
        do
          VERSION=$(grep "^${ARTIFACT_ID}:" versions.txt | cut -d':' -f2 | tr -d '[:space:]')
          TEMP_BRANCH="temp_branch_${ARTIFACT_ID}_$VERSION"
          git checkout -b $TEMP_BRANCH
          git rm .github/workflows/create_additional_release_tag.yaml
          git commit -m "Remove workflow file"
          git tag "${ARTIFACT_ID}/$VERSION"
          git push origin "${ARTIFACT_ID}/$VERSION"
          git checkout "$REF"
          git branch -D $TEMP_BRANCH
        done
