name: Create additional tags for each release

on:
  release:
    types: [published]
  workflow_dispatch: # If manually triggered, clarify which release to create the additional tags for
#    inputs:
#      releaseTag:
#        description: 'Release Tag'
#        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
#        ref: ${{ github.event.release.tag_name || github.event.inputs.releaseTag }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Create additional tag for google-cloud-shared-dependencies
      run: |
        ARTIFACT_IDS=('google-cloud-shared-dependencies' 'api-common' 'gax')
        for ARTIFACT_ID in "${ARTIFACT_IDS[@]}"
        do
          VERSION=$(grep "^${ARTIFACT_ID}:" versions.txt | cut -d':' -f2 | tr -d '[:space:]')
          TAG_NAME="${ARTIFACT_ID}/v$VERSION"
          if git show-ref --tags | egrep -q "refs/tags/$TAG_NAME$"
            then
              echo "Tag $TAG_NAME already exists. Skipping."
              continue
            fi
          git tag $TAG_NAME ${{ github.event.inputs.releaseTag }}
          git push origin $TAG_NAME
        done
