name: Create additional tag for each release with first_party_dependencies version

on:
  release:
    types: [published]
  workflow_dispatch: # If manually triggered, clarify which release to create the additional tag for
    inputs:
      releaseTag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: googleapis/sdk-platform-java
        ref: ${{ github.event.inputs.releaseTag }}
        GH_TOKEN: ${{ github.token }}

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Create additional tag
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f java-shared-dependencies/first-party-dependencies/pom.xml)
        git tag google-cloud-shared-dependencies/v$VERSION ${{ github.event.inputs.releaseTag }}
        git push origin google-cloud-shared-dependencies/v$VERSION